### ISSUE TITLE
Fuzzy Dates funktionieren nicht in der Themenübersicht

### ISSUE THREAD

**Issue by nlohmann** [nlohmann/lqfb_viewer#16]
Hier kommt es (z.B. in http://lf.nlohmann.me/themen/5) zu Anzeigen wie "seit Vor 1 Stunde".

**Comment by nlohmann** [comment]
Am besten dort gar keine Fuzzy Dates nutzen...

**Comment by svschannak** [comment]
Ja, bin gerade dabei das zu deaktivieren :horse:
