### ISSUE TITLE
gPlayer for Google Play Music

### ISSUE THREAD

**Issue by 26Itil** [nlohmann/lqfb_viewer#39]
HI nclohmann
I have a problem. In the weg on Google Play Music Desktop I can download music. When I start the app gPlayer for Google Play Music I can't download the music. Only for downloading the music I downloaded the app.
Thanks 
26Itil

**Comment by 26Itil** [comment]
why do you closed this issues?

**Comment by nlohmann** [comment]
It's unrelated to the project.

**Comment by 26Itil** [comment]
where I must write my problem?

**Comment by 26Itil** [comment]
I don't know GidHub so, I'm new. Help me who can help me.

**Comment by nlohmann** [comment]
I don't know.

**Comment by 26Itil** [comment]
nlohmann sprichst du zufälligerweise Deutsch? :)

**Comment by nlohmann** [comment]
Ja. Ich habe keine Ahnung wie du von "gPlayer for Google Play Music" auf dieses Projekt gekommen bist.

**Comment by 26Itil** [comment]
Ich habe Hilfe gesucht und habe ich im Internet GitHub gelesen und habe einen Account erstellt und da stand Issues und Googleübersetzer hat mir das als "Probleme" übersetzt.

**Comment by 26Itil** [comment]
lqfb_viewer
Keine Ahnung was das heissen soll :(
Wem müsste ich den Fragen der mir helfen kann?
