### ISSUE TITLE
Uhrzeit/Datumsausgabe aufhübschen

### ISSUE THREAD

**Issue by arbyter** [nlohmann/lqfb_viewer#8]
Sekundengenaue angaben braucht niemand. Stattdessen einen Filter schreiben, der das Datum jeweils in etwas umrechnet wie "vor 2 Stunden", "gestern", "20. März" und "März 2012" und so ausgibt. Erst beim MouseOver gibt es dann ggf. genaue Infos.

**Comment by nlohmann** [comment]
Macht man sowas in Javascript oder in den Templates?

**Comment by arbyter** [comment]
Das würde ich im Template machen, indem man dafür nen Templatetag schreibt der das dann umrechnet.

**Comment by svschannak** [comment]
http://timeago.yarp.com <- Lösung ;)

**Comment by arbyter** [comment]
Ja ne, das ist zu unpräzise! Ich hätte es schon gern wie oben beschrieben :)

**Comment by svschannak** [comment]
Tsss. Ich versuch mich mal dran.

**Comment by nlohmann** [comment]
Was ist da zu ungenau? Ich denke, dass passt genau.

**Comment by svschannak** [comment]
Zum Verständnis: 
Sekunden->Minuten->Stunden->gestern->Datum->Datum mit Jahr?

Also zum Beispiel nicht: vor 35 Tagen

Oder hab ich das falsch verstanden?

**Comment by arbyter** [comment]
Meine Idee: 
"gerade ebend" (innerhalb von 5min) -> "vor $minuten Minuten" -> "vor $stunden Stunden" (alles größer 60min && am aktuellen Tag") -> "gestern" -> "$Wochentag" -> $tag. $Monat_als_Wort -> $Monat_als_Wort $Jahr. Beim MouseOver das genaue Datum (ohne Sekundenangabe!).

**Comment by nlohmann** [comment]
Das finde ich sehr spezifisch. Das Framework finde ich gegenüber dem Status Quo eine Verbesserung, die sehr leicht (in dem Filter) eingebaut werden kann. Anschließend muss nur noch überall das JS eingebunden werden und fertig. Deine konkrete Forderung müsste man dann vielleicht durch was handgestricktes bauen...

**Comment by arbyter** [comment]
Darum meinte ich ja auch, dass diese JavaScript-Teil doof ist. Ich schreib jetzt selbst was. SO! ;)

**Comment by nlohmann** [comment]
![72f](https://f.cloud.github.com/assets/159488/341198/00478fac-9d69-11e2-911e-e858a99549e9.png)

**Comment by nlohmann** [comment]
Sehr schöner [Commit](https://github.com/nlohmann/lqfb_viewer/commit/d5cbe6f88fc9001163a98e99f2901b979337d9f7) von Sven. Mir fehlen noch
- Mouseovers
- etwas schöneres Unscharfwerden ("letzten Mittwoch", etc)
- überall außerhalb der Ereignisse genaues Datum

**Comment by svschannak** [comment]
Ich hab es mal ohne JS-Plugin gemacht:

https://github.com/nlohmann/lqfb_viewer/blob/d5cbe6f88fc9001163a98e99f2901b979337d9f7/server.py

Noch zu tun:
- [x] Wochentage anzeigen
- [x] Nur bei Ereignissen aktivieren
- [x] Monat als ausgeschriebener Name
- [x] Datum als Tooltip bei Mouseover

**Comment by arbyter** [comment]
Toll. Ich auch… Hach.

**Comment by nlohmann** [comment]
Cool, danke!
